# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import route_guide_pb2 as route__guide__pb2


class RouteGuideStub(object):
  """Interface exported by the server.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GenRepeated = channel.unary_unary(
        '/routeguide.RouteGuide/GenRepeated',
        request_serializer=route__guide__pb2.StreamDesc.SerializeToString,
        response_deserializer=route__guide__pb2.UniaryResponse.FromString,
        )
    self.GenStream = channel.unary_stream(
        '/routeguide.RouteGuide/GenStream',
        request_serializer=route__guide__pb2.StreamDesc.SerializeToString,
        response_deserializer=route__guide__pb2.StreamResponse.FromString,
        )


class RouteGuideServicer(object):
  """Interface exported by the server.
  """

  def GenRepeated(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GenStream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RouteGuideServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GenRepeated': grpc.unary_unary_rpc_method_handler(
          servicer.GenRepeated,
          request_deserializer=route__guide__pb2.StreamDesc.FromString,
          response_serializer=route__guide__pb2.UniaryResponse.SerializeToString,
      ),
      'GenStream': grpc.unary_stream_rpc_method_handler(
          servicer.GenStream,
          request_deserializer=route__guide__pb2.StreamDesc.FromString,
          response_serializer=route__guide__pb2.StreamResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'routeguide.RouteGuide', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
